### ISSUE TITLE
Hide GDPR cookies banners 

### ISSUE THREAD

**Issue by moshpirit** [duckduckgo/Android#1017]
These banners are very annoying and sometimes they take a big part of phone screens.

Extensions like "I don't care about cookies" hides these messages and make very much comfortable visiting internet websites.

**Comment by cmonfortep** [comment]
Thanks, I've listed this feature request under proposals for cosmetic filtering. However, we should analyze it from different points of view.

https://app.asana.com/0/0/1199610872492400/f

**Comment by moshpirit** [comment]
I have no asana account, what is this link? 😅

**Comment by cmonfortep** [comment]
@moshpirit asana is where we keep our internal backlog. This is something we may introduce at some point if we find a solution that we can integrate into our apps (e.g: an opensource library that we can use or our own implementation). 

I will close this ones since it has been added to our backlog, thanks.
