### ISSUE TITLE
Non webview version

### ISSUE THREAD

**Issue by NSTAdventure** [duckduckgo/Android#1046]
**Is your feature request related to a problem? Please describe.**
I disable webview for good reason as is owned by greedy data company #Google 

**Describe the solution or the user experience you'd like**
Maybe creating non Webview version?
I guess it work well

**Additional context**
I request this because you build DDG using webview as you say in my closed issues:
https://github.com/duckduckgo/Android/issues/1044#issuecomment-749993135

**Comment by cmonfortep** [comment]
Thanks. We don't have plans to move away from webview as it currently fits our needs and the cost is pretty high. We frequently audit our browser to detect any possible privacy implications. If you have detected any possible security issue, reach us via hackerone, it will go through our privacy expert team (see https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md#report-an-issue).

Btw, I really appreciate you responded back to us. Feel free to respond even if the issue was closed, that only means no action is required from our side, but if that changes we can always reopen the issue :)
