### ISSUE TITLE
Broken Site Error with DA

### ISSUE THREAD

**Issue by fractalaxy7** [duckduckgo/Android#1062]
**Description**
DuckDuckGo constantly returns a "This website could not be displayed." error when not scrolling on DeviantArt.  This error does not occur in any other browser.  DA is a very commonly used image platform.

**How to Reproduce**
Steps to reproduce the behavior.
*Update: Clear data with fire button first*
1. Type deviantart.com in search bar.
2. Accept cookies.
3. Wait a few seconds for error to occur.
4. See error.

**Smartphone**
App Info
 - Device: Moto G7
 - OS: Android 10
 - Version 5.73.0

**Comment by cmonfortep** [comment]
Hi, does that happen every time you visit that site? Asking this because I can't reproduce that issue on my device. Thanks.

**Comment by fractalaxy7** [comment]
Yes, I've tried opening the website in different ways, too, but the error always shows up.

**Comment by fractalaxy7** [comment]
I don't know if this is useful but occasionally, it also says the webpage cannot be displayed even when scrolling.

**Comment by cmonfortep** [comment]
Could you share with us a screenshot of the error you see? I assume when the error happens, you still see the website? Thanks.

**Comment by fractalaxy7** [comment]
![Screenshot_20210113-194456](https://user-images.githubusercontent.com/77362370/104501657-f021ab00-55d7-11eb-8801-5657b264d50a.png)
Also, I recently noticed that fully restarting the application without clearing the data (fire button) fixes the error until clearing the data again.

**Comment by cmonfortep** [comment]
Thanks for the screenshot. 

We show that message when the WebView renderer process has crashed internally. We are aware that it's something that can happen (that's why we have some logic in place to capture the event and allow users to reload the site), but the reason is unknown to us.

Sadly, it's not something I can reproduce on my personal or testing devices, and because of that, we can't open a bug report to the Webview team neither.

Thanks for reporting it, and we will use the information you provided to continue exploring this issue on our side.

**Comment by fractalaxy7** [comment]
OK.  Thanks for checking up on it.  I will find some more details of what went wrong and see if I can send it to the WebView (Google) developers.
