### ISSUE TITLE
Provide a sandboxed webapp functionality

### ISSUE THREAD

**Issue by summersab** [duckduckgo/Android#1073]
**Is your feature request related to a problem? Please describe.**
I think that Fireproofing websites is brilliant. I previously used it so I could create bookmarks of certain websites on my homescreen, use their mobile web page instead of their app, and periodically clear my browser's data using the Fire button. In this way, I could create "webapps" for certain services.

However, it doesn't provide a true sandboxed environment to prevent certain websites from tracking cross-site tracking. Many of these sites set cookies to allow tracking scripts on other websites to read them and track me even in other tabs. I can't truly create isolated "webapps" using DuckDuckGo.

**Describe the solution or the user experience you'd like**
Yesterday, I discovered this app, and it is brilliant:
https://github.com/tobykurien/webapps

With this, I can create more than just bookmarks of Fireproofed mobile web pages - I can create truly isolated, sandboxed webapps that actually appear in my app manager as separate apps. What's more, I can enable and disable any script I want on each page so I can allow the minimum required scripts for any website, and I can also specify if I want the mobile or desktop page by default.

I think DDG should seriously consider working with the developer, Toby Kurien, to provide a similar experience in the DDG Android browser. The privacy provided by his app is beyond what I could previously achieve with DDG alone. If this were to happen, there are a number of improvements that could be made:
- Ability to clear the cache and history of the current webapp
- Provide a "store" of pre-configured webapps (or allow users to easily share them with others while ensuring that login cookies are cleared)
- Provide a better "long-press" context menu to allow things like copying/sharing the address of a link in the app
- Drag down to refresh pages
- Access to the URL bar of the website

**Comment by cmonfortep** [comment]
Thanks for sharing that with us. Actually, that's something we thought about and we will explore in the future.  It's a bit complex due to some WebView limitations. Not impossible for sure, but we need to find the right balance between user experience and how to solve the problem knowing those limitations (e.g: WebView works with a single cookie manager create internally by the component, so we can't provide a different one for each "sandboxed site").

I will close this issue since it's something we already have in our backlog. Thanks again to share that project with us, and kudos to that dev for providing a nice solution to protect users.
