### ISSUE TITLE
Saved bookmark triggers app search instead of loading site

### ISSUE THREAD

**Issue by woheller69** [duckduckgo/Android#1104]
**Describe the bug**
When the browser finds a bookmark it does not use the "https://" part of the bookmark. Some pages will not load.

**How to Reproduce**
1. Go to https://f-droid.org/wiki/index.php?title=Special:RecentChanges&days=7&from=&hidebots=0&hideanons=1&hideliu=1&limit=500
2. Set page as bookmark
3. Search for "recent". It will show bookmark in search results
4. Click on search result
5. Page will not open
6. It works, however, if another https:// is added to the bookmark. So https://https://f-droid....

If applicable, please include information about any settings that may be relevant to this issue (e.g. selected theme, auto clear option, etc).

**Expected behavior**
Page should be loaded

**Smartphone (please complete the following information):**
 - DDG App Version: 5.76.1
 - Device: Samsung Galaxy Tab A7
 - OS: Android 10
 - If applicable, add screenshots to help explain your problem.

**Comment by cmonfortep** [comment]
Thanks for reporting this one. 

I've been playing around with my bookmarks and I was not able to reproduce the issue. However, it's true for the link you posted. After taking a look, it seems we are not parsing correctly the bookmark URL for that concrete case. Removing `title=Special:RecentChanges` fixes the issue. It seems we are not parsin the schema correctly because the `:` character in the URL.

I will create a bug task in our backlog to provide a fix. Thanks.

**Comment by marcosholgado** [comment]
I think this might be fixed with https://github.com/duckduckgo/Android/pull/1247, I'll try to recreate next week with those changes but "in theory" bookmarks should now always load a url and never do a search.

**Comment by woheller69** [comment]
works now
