### ISSUE TITLE
After Upgrade from 5.68 to 5.77.1 all bookmarks are deleted

### ISSUE THREAD

**Issue by WST1811** [duckduckgo/Android#1109]
**Describe the bug**

Delete all bookmarks after Upgrade from Version 5.68 to 5.77.1

**How to Reproduce**

Install 5.68 add some bookmarks, upgrade to 5.77.1.

If applicable, please include information about any settings that may be relevant to this issue (e.g. selected theme, auto clear option, etc).

**Expected behavior**

Alle bookmarks are gone after upgrade.

**Smartphone (please complete the following information):**
 - DDG App Version: (e.g. 5.25.0) Version can be found:
     - DDG App settings: Settings -> Version
     - System settings: Settings -> Apps & notifications -> App Info
5.77.0

 - Device: [e.g. Pixel 2, Samsung s10]

Samsung Galaxy S5

 - OS: [e.g. Android 10]

LineageOS 17.1 (17.1-20210214)
Android 10

**Comment by cmonfortep** [comment]
Hi @WST1811 I've just followed the "how to reproduce" steps and bookmarks were preserved on my device, so I can't reproduce this bug.

I've just quickly checked recet user feedback and I couldn't found any comments/feedback related to bookmarks neither.

**Comment by WST1811** [comment]
How i get my bookmarks back?

**Comment by cmonfortep** [comment]
Hi @WST1811 we don't provide a way to recover bookmarks because they are only stored locally on your phone. Apologies if they have been removed, I agree this should not happen and we will review what could have caused that problem. The only thing I can think about is some kind of error in the database, but we are not aware of any bug at that level.

Sorry again for the issue.

**Comment by WST1811** [comment]
Thanks for Answer. Can i save the Database and/or look in the Database? Which file contain the Database?

**Comment by yaanahuu2** [comment]
+1 all gone.
