### ISSUE TITLE
"Clear" button to be positioned at the left side of the bar

### ISSUE THREAD

**Issue by moshpirit** [duckduckgo/Android#1212]
The current state of the top bar is:

`URL bar` `clear button` `tabs` `menu`

I think it's fair to think that some people may have an issue with the clear button being located at the right side of the bar, just near the tabs an issue because a misclick can screw all the open tabs without any warning. Including a warning message can be annoying for wanted clear clicks and the URL bar is huge so it's easier to press (I always press the middle of the bar, never the right side).

The only problem I see with this design is that the clear button is less accessible for one right hand usage of the phone but it can be very easily fixed by giving us the option to move the bar to the bottom of the screen as Firefox does (which I find very comfortable to use btw)

**Comment by Ammako** [comment]
Eh. Pass. It's not possible to accidentally clear all your open tabs without warning, because, there is a confirmation box when you press that button, and that's fine.

If you move it elsewhere and remove that confirmation box, then it becomes easy to genuinely just wipe everything by accident. You can already clear without confirmation by setting it to automatically clear tabs and data on app exit. Then all you have to do is swipe away the app on app switcher whenever you're done, and you never really need to use the fire button.

**Comment by moshpirit** [comment]
You are right, sorry idk why I forgot about the confirmation box lol

**Comment by cmonfortep** [comment]
Thanks for reaching us. We are currently only accepting Github Issues for bug reports. Additionally, as commented above, we already show a confirmation dialog to avoid clearing data if the user presses the fire button by mistake.

Please, use discussions to share feature requests. Only bug reports are expected to be accepted as issues. Thanks.

[Contributing guidelines](https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md#contribute-code)
