### ISSUE TITLE
Geckoview

### ISSUE THREAD

**Issue by Github-com-foss** [duckduckgo/Android#1282]
Pls adopt geckoview engine and support opensource project. I know webview is opensource but dont depend google. Pls make full featured browser.

**Comment by WillHick** [comment]
DuckDuckGo isnt based on Chromium, it uses the WebView component in Android, almost sure they said they are not going to use GeckoView but id like to see something better than WebView 🤣

**Comment by lucifiel** [comment]
Option to use alternative webview would be nice. There are devices that are stuck with vendor supplied implementation.
For example huawei and honor devices are shipped with com.huawei.webview (based on 2018 code) and reject other non-huawei signed versions.

**Comment by Ammako** [comment]
Not necessarily a bad suggestion, but GeckoView is not a WebView replacement, so it would be a lot of work to make the app compatible with it (and would increase the size of the app because it would need to ship with GeckoView.)

Not that they wouldn't do it, but it would be up to them to decide if that's worth the dev time. For everything else, I'm not sure if it's possible to bundle webview inside an app instead of using the build-in webview provider. But if that's possible then I guess they could always ship with Bromite WebView and that would be good enough, but then they'd also need to make new releases even more regularly to cover WebView updates, and may also significantly increase the build times. Otherwise it's not really possible for an app to override the system's webview provider.

**Comment by cmonfortep** [comment]
Thanks for reaching us. We are currently only accepting Github Issues for bug reports.

Please, use discussions to share feature requests. Only bug reports are expected to be accepted as issues. Thanks.

[Contributing guidelines](https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md#contribute-code)

**Comment by rugk** [comment]
> but GeckoView is not a WebView replacement

I guess they kinda aim to be that…

from their website at https://mozilla.github.io/geckoview/:
> GeckoView is designed to expose the entire power of the Web to applications, and all that through a straightforward API. Think of it as harnessing the full power of Gecko (the engine that powers Firefox), while its API is WebView-like and easy to use.
