### ISSUE TITLE
Android mobile browser is blocking Plyr JS video player

### ISSUE THREAD

**Issue by shum16** [duckduckgo/Android#1296]
**Describe the bug**
It seems like the DuckDuckGo Android mobile browser is blocking the Plyr video player, at least with youtube content. Please look at this link in the browser: https://plyr.io/#youtube - the video is not just playing. The point is that we are using this player for our website (here, for instance: https://changeonelife.ru/videoprofiles/egor-m-respublika-bashkortostan-3/) and our users have recently started to complain about that.

IOS version seems not to have such problem.

**How to Reproduce**
1. Go to https://plyr.io/#youtube
2. Click on Play video
3. See that video is not playing

If applicable, please include information about any settings that may be relevant to this issue (e.g. selected theme, auto clear option, etc).

**Expected behavior**
Video should play fine like in Chrome browser.

**Smartphone (please complete the following information):**
 - DDG App Version: 5.89.1
 - Device: Honor 8 Pro
 - OS: Android 9

**Comment by cmonfortep** [comment]
Thanks, @shum16 for reporting this. This seems related to the same issue we detected on some other sites related to DRM permissions. (see https://github.com/duckduckgo/Android/pull/1291)

Our privacy team needs to validate if we can add this site to our allow list. Please report the issue directly from the DDG browser app, and they will investigate it.

Steps to report the issue:
1. Go to https://plyr.io/#youtube
2. click on the "..." button
3. click on "Report broken site"

Thanks. I will close this issue since it will be addressed internally by our privacy team.
