### ISSUE TITLE
Problem with File Names in Downloads

### ISSUE THREAD

**Issue by ghost** [duckduckgo/Android#1312]
**Describe the bug**
- DDG browser doesn't name the files as expected. 
- The inner content remains unchanged. The main problem is with the file name and its extension
- The file name doesn't matter to it and always names it as `uploads`.

I tried to download following type of files  from [here](https://ddg-name-test-ubsgiobgibsdgsbklsdjgm.netlify.app/) and resulted as follows:

| original file | path | named file |
| --- | --- | --- |
| File.py | uploads/***/ | uploads.txt |
| File.c | uploads/***/ | uploads.txt  |
| File.js | uploads/***/ | uploads.js |
| File.txt | static/***/ | static.txt |
| FilewithnoExt | uploads/***/ | no name or uploads.bin|

> I'll try to update this table in future by adding file names when I encounter any issue.

**How to Reproduce**
1. Download the following type files(original file) and the browser will ask you to save them in the following type files(named file)

**Expected behavior**
Download the file with correct name

**Smartphone:**
 - DDG App Version: 5.89.1
 - Device: Xiaomi
 - OS: Android 10

**Comment by aitorvs** [comment]
Thanks for reporting this @Lalisfeed. This should have been fixed in the latest DDG app v5.90.0. Could you tell us if it still happens when you upgrade?

cc @cmonfortep @malmstein

**Comment by malmstein** [comment]
@Lalisfeed would you be able to share the links you're using to download those files? Just the name + extension is not enough to solve the issue.

**Comment by Lalisfeed** [comment]
@malmstein  I added it in the above comment.

**Comment by Lalisfeed** [comment]
@aitorvs I checked this by installing 59000. I see these:
- complete file name disappears sometimes in the popup which says ` Save filename `
- still see the  `uploads` word , ex: abcd.c as uploads.txt

When I inspected the ` href  ` url in the html ` a` tag, I saw that ddg might have named the file based on the url but not based on the file name.

ex:  if the file `text.js` is in `https://www.example.com/uploads/djfkrkgksiciie488edkgkk3kfkdkskgkfjkwkfkdksk/text.js`, then ddg takes the `uploads` name which is at the beginning and  `.js`  which is at the end and names it. So that's where the error comes from I think. If I'm wrong please correct me

**Comment by Lalisfeed** [comment]
@aitorvs I made this explaination better in the site itself. check [this](https://ddg-name-test-ubsgiobgibsdgsbklsdjgm.netlify.app/)

**Comment by Ammako** [comment]
Isn't that #1018? Yeah, not fixed in 5.90.0

Had no idea 5.90.0 was supposed to be fixing this... might be nice to actually describe what updates do instead of just "rearranging the furniture", you know?

**Comment by Lalisfeed** [comment]
Its working better than before. 
media.bin -> media.png (5.90.0)
file extension naming goes well but file prefix naming is still done based on `media/`.

**Comment by sunriver** [comment]
![Screen Shot 2021-08-10 at 3 31 25 PM](https://user-images.githubusercontent.com/1295939/128972251-c7f29caa-09ab-4338-b255-13b481d877ad.png)

**Comment by vatonbero** [comment]
Still affects `v5.102.3`, if anyone is keeping tabs.

**Comment by varaki** [comment]
Yes, issue still exists, really annoying.
