### ISSUE TITLE
[Bug] Cyclic open system window "Set as default"

### ISSUE THREAD

**Issue by mr-back-to-python** [duckduckgo/Android#1396]
### Describe the bug

While Dark Mode is on switch to Light theme leads to cyclic open system window "Set as default".

### How to Reproduce

1. Go to Settings
2. Click Light theme ("Светлая тема") when turn on Dark Mode

### Expected behavior

Switch to Light theme

### Environment

```markdown
- DDG App Version: 5.93.0
- Device: Nokia 5.3
- OS: Android 11
```

**Comment by Shawlaw** [comment]
This bug has been fixed in https://github.com/duckduckgo/Android/pull/1365
Starting with v5.94.0 the bug should has been fixed, you can update your app to the latest version.
It is because changing theme would cause current Activity recreate and restore previous Switch widgets' status, which triggers the corresponding onCheckChangeListener.
Unfortunately the listener in v5.93.0 doesn't handle this case properly so it will cause this bug.
