### ISSUE TITLE
[Feature] Ability to create bookmark folder from (edit screen) EditSavedSiteDialogFragment -> BookmarkFoldersActivity

### ISSUE THREAD

**Issue by 4shutosh** [duckduckgo/Android#1439]
**Feature Description**
Users should be able to create a new folder from the EditSavedSiteDialogFragment/edit screen, which is much more convenient than going back to the bookmarks screen and creating a folder and then going back again to select that folder for the bookmark.

Even if the user goes to the bookmarks list screen and then wishes to check the folder there is no add folder directly from the edit screen. The user will need to come back to the parent list screen and then add the folder and then go back to update the bookmark location.

**Suggested Behaviour**
Giving add folder option on the BookmarkFoldersActivity solves the above problem.

**Comment by cmonfortep** [comment]
Hey @4shutosh it's a nice idea.

However, please open a discussion for this one (you can add also https://github.com/duckduckgo/Android/issues/1440 in the same discussion since they are both related) to suggest any bookmark improvement. 

As per our [contributions guidelines](https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md#contribute-code), we only accept Bug reports as Issues.
