### ISSUE TITLE
Custom Tabs instead of webview

### ISSUE THREAD

**Issue by rugk** [duckduckgo/Android#146]
I see you still use webview sometimes. 

Why not use Chrome/ium, respectively, Firefox Custom Tabs (the two browsers, I know, which support that feature) instead of WebViews?

**Comment by CDRussell** [comment]
Thanks for the suggestion.

The decision to use `WebView` was made mostly due to existing familiarity with it and that we knew we'd be able to use it and have the full control over it that we need to offer all of the functionality in the app.

It might be possible to achieve everything using custom tabs, but it would have taken longer to explore that route. There are some things offered in custom tabs that might be seen as a feature but that we might not want for our app. For instance, the sharing of cookies between custom tabs and Chrome might not be something we immediately want given the privacy-focussed nature of this app.

But `WebView` isn't set in stone. We'll explore how to continue making the browsing experience better. I'll close this ticket now as a we have a plan to further investigate Chromium anyway, so we'll also look at custom tabs then too.

Thanks

**Comment by nbrr** [comment]
@CDRussell Webviews will soon be deprecated for use with Facebook login SDK, [see](https://developers.facebook.com/docs/facebook-login/android/deprecating-webviews), and only Custom Tabs will be usable. Has any kind of Custom Tabs support been added since this issue was initiated?

**Comment by beedell-roke** [comment]
Perhaps, utilise https://github.com/commons-app/apps-android-commons/issues/1143#issuecomment-365542341 as a reference.
