### ISSUE TITLE
[Bug] browser hangs before rendering anything

### ISSUE THREAD

**Issue by sandeep-gh** [duckduckgo/Android#1471]
### Describe the bug

I uninstalled and reinstalled the DDG browser. Machine as internet connection. Irrespective of the url, the browser get stuck midway somewhere between fetching content and rendering. 

### How to Reproduce

Nothing much other than entering url. 

### Expected behavior

![Screenshot 2021-10-08 11 41 50](https://user-images.githubusercontent.com/24786309/136507619-2c780fdf-2030-46a9-9d4e-3d0c63587d85.png)

### Environment

```markdown
- DDG App Version: 5.97.0
- Device: Lenovo Duet
- OS: Chrome OS
```

**Comment by sandeep-gh** [comment]
After I did a powerwash of my tablet, DDG browser has been working smoothly. So is the firefox for android beta.

**Comment by cmonfortep** [comment]
Closing this one as we haven't received any more feedback related to that.

**Comment by hypeJunction** [comment]
This started happening to me now. The only clue is that I enabled a work profile. 
![Screenshot_20250102-190447](https://github.com/user-attachments/assets/1c246e19-eb2c-41be-aa19-c630fdfebb7a)

**Comment by Alatarius** [comment]
I just started having this issue after the latest update. I thought it was my connection but when I am on wifi with a solid connection, it still happens when I try to navigate to a site either by manually entering a url or clicking a link from the search page. Only the search page will load completely. All sites themself stop loading at the 50% mark.
