### ISSUE TITLE
google now action needs work

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/android#149]
When I open via the Google now swipe up, it should always open in search mode with the keyboard up. It's been pretty inconsistent for me.

**Comment by sreilly** [comment]
I still get issues with this one.  It does open in the right mode, although the keyboard is often not visible until I tap in the search field.

It also seems to stick the app into search mode with no obvious way to get out of it.  I think the difference is that the bang button is an action button in search mode whereas it's used to exit most other modes. You can get back to the stories/recents/favourites mode by tapping the back button though, but it takes two taps: one to hide the keyboard, and one to actually go back.

Could it be changed so that the back button hides the keyboard as well as takes you back a level?  I think that would make sense it doesn't seem useful to hide the keyboard but remain in the search mode, does it?

**Comment by nilnilnil** [comment]
I agree. I replaced this with #159. I like your idea of making the keyboard & search box relinquish one back button tap.
