### ISSUE TITLE
[Bug] Autocomplete completely disabled

### ISSUE THREAD

**Issue by Krzmbrzl** [duckduckgo/Android#1590]
### Describe the bug

I'm not sure why, but when using the DDG app, I don't get any autocomplete support from my keyboard (AnySoftKeyboard) when typing in the URL bar. The same applies for some other fields such as the title field for this issue, whereas at other places (e.g. while writing this text in the issue body) autocomplete is back working normally.

My best guess is that DDG uses some special input form or flag for these fields which prevent the keyboard from using autocomplete.

Personally I consider this a bit annoying and it would be great if this behavior could be changed (either globally or via a setting).

Note: Previously I was using Firefox for Android and there, I did not notice such a behavior (keyboard was the same).

### How to Reproduce

Open DDG and start typing in URL bar

### Expected behavior

Autotype to be working 

### Environment

```markdown
- DDG App Version: 5.98.1
- Device: Shiftphone 6m
- OS: Android 8
```

**Comment by cmonfortep** [comment]
Sorry @Krzmbrzl. This is by design. Your assumption is correct, we use a special flag to indicate keyboards they should use private mode when using our browser.

We are considering allowing users to opt-out from settings, but we are still discussing that.

Closing this issue as not a bug.

**Comment by Krzmbrzl** [comment]
Ah so the keyboards are instructed to use private mode and are not explicitly instructed to not use autocomplete? In that case I might also create a request for my keyboard to support "private autocomplete" (aka without learning any words).

In opt-out inside DDG would ve great though. Where is the discussion about this taking place? Maybe I could get involved there.

**Comment by cmonfortep** [comment]
@Krzmbrzl that's correct. Every keyboard will honor private mode in a different way.

Here you have a link to the official docs: https://developer.android.com/reference/android/view/inputmethod/EditorInfo#IME_FLAG_NO_PERSONALIZED_LEARNING

The discussion is taking place internally since we are having discussions about privacy implications, and how to mitigate them.

**Comment by Krzmbrzl** [comment]
Roger that - thanks for the info!

**Comment by translatingtheirtruth** [comment]
Please, could you please resolve the issue about 'autocorrect' and 'suggestions' on the URL bar, and search bar of the browser.  This also happen in Brave browser, and dictionary apps like Farlex The Free Dictionary. 
Please,  it's so difficult to use the keyboard without corrections because my fingers are fat and O can't type fast or accurate as in Swiftkey.

**Comment by translatingtheirtruth** [comment]
Please fix this, because it's so annoying delate and correct letter by letter when using URL or search bar in DDG

**Comment by danaYatsuta** [comment]
Could we please get an update on this? The lack of this feature really hinders DDG browser usage experience, and I feel like as long as security concerns are communicated to the user, having the choice would be an improvement.
