### ISSUE TITLE
VPN Stops

### ISSUE THREAD

**Issue by aswedaw** [duckduckgo/Android#1595]
Here in Myanmar, we need to use VPNs to access the internet.
No two VPNs work at the same time on Android. When we enable App Protection,VPNs stop as App Protection function s as a VPN. So,we have to disable this function. How about publishing a Standalone DuckDuckGo VPN app as the browser doesn't work as the full functions of a VPN. It tunnels all apps only.

**Comment by aitorvs** [comment]
Hey @aswedaw, thanks for raising this point. We are aware of this and discussing internally the best way forward.

A bit of admin, I will close this issue here because it is more a feature request and those should be in the discussions section, see [contributing](https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md) guidelines.
