### ISSUE TITLE
The release notes contain no information

### ISSUE THREAD

**Issue by graue70** [duckduckgo/Android#1824]
The release notes of the last nine releases say the exact same thing which renders them close to useless in my opinion. I know it's additional work but still I would highly appreciate proper release notes. Even automatic release notes created from the pulled PRs and/or commits would be more helpful than how it is currently done.

**Comment by cmonfortep** [comment]
Thanks for the feedback. I can share this internally with the team.

I'm going to close this issue because we are currently only accepting Github Issues for bug reports.

Please, for future feedback notice you can use our in-app feedback form, or feel free to open a discussion instead. Thanks.

[Contributing guidelines](https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md#contribute-code)
