### ISSUE TITLE
[Bug] window height with address bar

### ISSUE THREAD

**Issue by Jehfen** [duckduckgo/Android#1997]
### Describe the bug

The window height with address bar is not correct.
You should support css fill-available (or stretch)

### How to Reproduce

go to a website on a mobile device. 100vh (100% height) containers are higher than the screen, because the height of the address bar is not subtracted from the available height.

### Expected behavior

When using css fill-available the correct height should be used

### Environment

```markdown
- DDG App Version: latest
- Device: recent smartphone
- OS: Android
```

**Comment by cmonfortep** [comment]
Duplicated: https://github.com/duckduckgo/Android/issues/914

**Comment by aarongarciah** [comment]
This issue seems to be still relevant. DuckDuckGo reports a higher viewport height than Chrome on Android on the same device. See the screenshots below and the rendered value for `window.innerHeight`.

Apart from that, Chrome updates the `window.innerHeight` value when the viewport is scrolled, and the top navigation bar is hidden. `window.innerHeight` doesn't get updated in DuckDuckGo when the viewport is scrolled and the top navigation bar is hidden.

This issue causes `-webkit-fill-available` and the newer [`dvh` and `svh` CSS viewport units](https://web.dev/viewport-units/) to not work properly. `100vh`, `100dvh` and `100svh` always result in the same size.


|Chrome|DuckDuckGo|
|---|---|
|<img src="https://github.com/duckduckgo/Android/assets/7225802/f406baae-3351-471b-acc4-f280ba2e09d9" alt="Chrome" width="320" />|<img src="https://github.com/duckduckgo/Android/assets/7225802/4428f863-0530-444f-b158-4b9bdc18b9c6" alt="DuckDuckGo" width="320" />
