### ISSUE TITLE
[Bug] Nonfunctioning cookie consent pop-up handling at The Onion

### ISSUE THREAD

**Issue by Ammako** [duckduckgo/Android#2468]
### Describe the bug

Duckduckgo's handling of cookie consent popup does not work at The Onion.

### How to Reproduce

Visit https://www.theonion.com/

### Expected behavior

It should detect the cookie consent popup and automatically deny as much of it as it can, as designed.

### Environment

```markdown
- DDG App Version: 5.141.0
- Device: Pixel 4a
- OS: Android 13
```

**Comment by cmonfortep** [comment]
Thanks, @Ammako. We are aware that our cookie prompt management feature is not capturing all the cookie popups out there. We really appreciate the bug report.

About how to report them, I think creating a GitHub issue for each individual site will be too much. If you find more non-supported sites, feel free to post them as part of this issue. Having something in-app sounds great, I have some ideas that I will propose with the team.

I'm closing the issue since we are internally working on new improvements to support more types of cookie prompts that will increase the current coverage.
