### ISSUE TITLE
[feature request] blocking internet access for some apps entirely using tracking protection

### ISSUE THREAD

**Issue by mmahmoudian** [duckduckgo/Android#2661]
## A bit of background
I have been using the tracking protection for few days now jut to see what app try to send what to where, but due to how Android VPN works, the DDG tracking protection "replaced" the NetGuard (I know "replaced" is not accurate). [NetGuard](https://github.com/M66B/NetGuard) let the user to add apps to black-list and white-list for WiFi and GSM internet access.

## Suggestion
It would be super useful to, similar to NetGuard, let the user to completely cut off internet access to certain apps. This would bring much better control to user and subsequently provides the possibility of a safer experience for the user.

**Comment by aitorvs** [comment]
Hello @mmahmoudian, thanks for reporting this. 

If I understand correctly, you're suggesting a feature where if an app is not "protected" then it won't have internet access to avoid leaking.

We don't offer that feature at the minute, because it's problematic in some levels. You can always do that using Android VPN settings directly, ie. Android VPN settings -> Advanced -> VPN -> Gear button for DuckDuckGo -> enable both always on AND "block connections without VPN"

Although we encourage users to enable "always on", we **discourage** enabling "block connections without VPN" along with it. Because its effects can be missinterpreted as breakage.

**Comment by mmahmoudian** [comment]
@aitorvs Thanks for your reply. But no, that's not what I meant. Perhaps the easiest way is to explore how NetGuard (which is FLOSS under GPLv3) works.

But for the sake of argument I try to explain with an example:

I have some applications that I don't use frequently or their operations does not depend on internet access. In this situation, there is not point is letting them access internet either when they are not in use, or when they should operate regardless of internet access. For instance, a calculator app does not need to access internet to operate, therefore, logically it would be safe to completely cut their internet access.

By this feature that I suggested, user will be able to toggle a button in DDG tracking protection settings and tell DDG to drop all packages to and from this app. This would give more control to user and would drastically improve safety and privacy.

**Comment by aitorvs** [comment]
Thanks @mmahmoudian, makes sense. 

We don't have plans to support that at the minute.

Closing this issue for now. If you want to keep this open and continue a discussion about it, feel free to open a [Discussion](https://github.com/duckduckgo/Android/discussions).

**Comment by pabloscloud** [comment]
One can't open a discussion anymore. I'd still love to see this
