### ISSUE TITLE
[Bug] Horizontal swipes always translate the toolbar

### ISSUE THREAD

**Issue by Mugurell** [duckduckgo/Android#2800]
### Describe the bug

Various popular websites contain iframes or scrollable elements that if scrolled should not also animate the toolbar.
This is probably an impossible bug to tackle at the moment as a wrapper over `WebView`.

A comparison of DDG and Chrome:

https://user-images.githubusercontent.com/11428869/215857912-02cf6698-2f5e-4b38-ac64-9eb200bff5bd.mp4

### How to Reproduce

1) - visit `youtube.com` and scroll horizontally (just slightly on the vertical) in a horizontally scrollable element
2) - visit `maps.google.com` and scroll the map horizontally or even vertically.

### Expected behavior

The toolbar should not be animated.

### Environment

```markdown
Happens on all devices and all DDG versions.
```

**Comment by cmonfortep** [comment]
Thanks. It's a known limitation, scroll behavior on webview is problematic and I don't think we can tackle it without fixing first https://github.com/duckduckgo/Android/issues/914, but we never prioritized that task. Until then, any vertical scroll will translate to the toolbar.

On your video, the toolbar hides because of the vertical scroll you apply. A horizontal scroll doesn't translate to the toolbar.
