### ISSUE TITLE
Feature request: Support FIDO2, etc.

### ISSUE THREAD

**Issue by sjvudp** [duckduckgo/Android#2823]
When wanting to use a YubiKey, I have to use the Chrome browser in Android, because DuckDuckGo does not detect the YubiKey (e.g. the 5C NFC via NFC).

Sample page: https://demo.yubico.com/webauthn-technical/registration

**Comment by malmstein** [comment]
Thanks for reporting, this is not in our plans for now.

**Comment by sjvudp** [comment]
So you "recommend using Google Chrome instead"? ;-)

**Comment by NeoTheFox** [comment]
Can I ask for a reconsideration of this? 
Since you can fireproof websites now, DuckDuckGo had been my default browser for a while, but other apps embed the default browser to log-in (example - OpenCloud), and that means to log into apps that support my FIDO2 keys I have to make another browser the default first, then do the auth, then make DuckDuckGo the default again. This is very cumbersome, and I can't log in and fireproof on DuckDuckGo.

**Comment by Node815** [comment]
In my humble opinion, the Duck Duck Go browser would be the KING of ALL Browsers if they enabled it.  I have uninstalled it becuase of this as most my sites are not supported due to Fido2/WebAuthn not working.
