### ISSUE TITLE
[Bug] HTML5 Time picker styling issues

### ISSUE THREAD

**Issue by LKPridgeon** [duckduckgo/Android#2976]
### Describe the bug

We recently had some users report issues with selecting time on our website with users struggling to find the "OK" button on the time selector. 

After some investigation we discovered an issue with the DuckDuckGo browser. The time wheel is clearly visible however the buttons aren't visible and the backgroud isn't following the device theme.

![Screenshot_20230318-124132](https://user-images.githubusercontent.com/6911864/226106866-b59ca2a0-5b82-44e8-8df3-358be48e8246.png)

### How to Reproduce

On an Android mobile device open DuckDuckGo and:
1. Go to https://www.fastjp.com
2. Press the time input (4th input in the "Plan a journey" box)
3. Observe incorrect background and missing action buttons

We have only tested with Android 12 & 13. 

### Expected behavior

The background should follow the system theme and action buttons clearly visible. 

Screenshot of expected output from Firefox Mobile:
![Screenshot_20230318-124429](https://user-images.githubusercontent.com/6911864/226106886-21351248-eb7f-4b94-803b-44687d688fcf.png)

### Environment

```markdown
- DDG App Version: 5.152.0 ml (51520000)
- Device: Sony Xperia 1 IV - XQ-CT54
- OS: Android 13 (64.1.A.0.882)
```

**Comment by malmstein** [comment]
Thanks for reporting @LKPridgeon , I'll take a look!

**Comment by dryaz** [comment]
@malmstein 

Consistent fix of invisible buttons according to current code base is to add

`<item name="android:timePickerDialogTheme">@style/Widget.DuckDuckGo.TimePicker</item>`

along with 

`<item name="android:datePickerDialogTheme">@style/Widget.DuckDuckGo.DatePicker</item>`

into `design-system-theming.xml` which will fix the issue and align date and time pickers together:

<img width="346" alt="CleanShot 2023-06-04 at 00 19 31@2x" src="https://github.com/duckduckgo/Android/assets/1395176/e82dd764-31e2-4557-b130-4bf0c5edbe03">

But DatePicker theme is not correct dark/light wise (according to system UI).
Here's the definition of what colors used where:
https://m2.material.io/components/date-pickers/android#anatomy-and-key-properties

In DDG you don't change bg color with dark one and keep both pickers whit/blue in both modes but yet change font color.

In order to change BG of calendar view you could use `windowBackground` which changes that white calendar BG.
