### ISSUE TITLE
Missing an important function.

### ISSUE THREAD

**Issue by edentw** [duckduckgo/Android#329]
HI,
Lack of whitelist function inside, hope to add him in!

**Comment by CDRussell** [comment]
We do allow individual websites to be whitelisted so that the protection isn't applied to them; you can access that from the privacy grade option (to the left of the URL bar).

![screenshot_20180824-122712](https://user-images.githubusercontent.com/1336281/44582339-3a9cf580-a799-11e8-940e-8a0e7c4e35d5.png)

Or is it another type of whitelist you're looking for? If so, please elaborate.

**Comment by edentw** [comment]
![d](https://user-images.githubusercontent.com/41664010/44583785-5c1dd180-a7d9-11e8-814a-b2f592dc3bbe.jpg)
