### ISSUE TITLE
Add To Home shortcut not working for some Launchers

### ISSUE THREAD

**Issue by CDRussell** [duckduckgo/Android#365]
We added the "add to home" shortcut functionality, originally captured in #224 

Since then, some users have reported that it's not working for them. Let's capture some data about which Launchers are not working to see if it's specifically a Launcher problem or something else.

### Reported Launchers

- Fastkey launcher
- Launcher3 (Android 7.0 / Blackview 6000)
- Apolo

**Comment by In2deep73** [comment]
I can confirm that the two launchers mentioned here as well as Apolo launcher are not working for me on a Samsung Galaxy S8 (8.1) and a Google Pixel XL (9.0).

**Comment by CDRussell** [comment]
**Tested on a Samsung S6 (Android 7.0)**
✅ Fastkey 
✅ Apolo

**Tested on a Pixel 2 (Android 9.0)**
👎FastKey
👎Apolo

It seems that the shortcut is created, but not on the Launcher you'd expect - it adds it to the default `Pixel Launcher` every time you create one.

I don't know what the solution is yet, though.

**Comment by arunsathiya** [comment]
I tested this further and when using Fastkey launcher, the shortcut is not crested - both on DuckDuckGo and Google Chrome for Android. It's interesting that it works for @cdrussell on Samsung S6 though.

I've also shared this GitHub issue link with the developers of Fastkey on email, to share any ideas they might have.

**Comment by CDRussell** [comment]
@arunsathiya what OS version are you using? I suspect the problem only exists on newer versions of Android, maybe Oreo and newer.

**Comment by arunsathiya** [comment]
@CDRussell I am on Android 8.1.0 at the moment. Also noting that it's a OnePlus 5, which might be offering a flavoured version of Android, not stock.

**Comment by In2deep73** [comment]
I looked into this some more and it appears that `ShortcutManagerCompat.isRequestPinShortcutSupported(context)` returns `false` when using launchers that do not support the add to home feature (which includes the launchers we confirmed as not working on Android 8+; it seems to return `true` on older Android versions using said launchers, however).

Since other competing browsers seem to also have this issue with the launchers we've tested, and given @CDRussell's  experience with the add to home feature behaving unpredictably on certain launchers (i.e. making a shortcut on an inactive launcher - not cool!), I think maybe it would be best to either do the `ShortcutManagerCompat.isRequestPinShortcutSupported(context)` check on button click and handle it there or update the view model `canAddToHome = true` to use the result of `ShortcutManagerCompat.isRequestPinShortcutSupported(context)` instead of `true`, which I believe will effectively "grey it out" for unsupported configurations, though I have not tested this.

If you like these ideas and do not have time to implement/test them, I would be happy to implement and thoroughly test these approaches.

For reference: https://developer.android.com/reference/android/support/v4/content/pm/ShortcutManagerCompat

**Comment by CDRussell** [comment]
Thanks for the info, @In2deep73. You are very much right that we should be checking `ShortcutManagerCompat.isRequestPinShortcutSupported(context)` which we aren't currently doing.

This will return false when the current Launcher doesn't support the shortcut. If your favourite Launcher doesn't currently support them, that's an issue for the Launcher to resolve (if it wants to), and there's nothing further we can do to force it on them.

So it seems there are two parts of this problem:

1. The app needs to check `ShortcutManagerCompat.isRequestPinShortcutSupported(context)`
1. Launchers themselves need this permission `com.android.launcher.action.INSTALL_SHORTCUT` to support shortcuts. If anyone is raising an issue with a Launcher about this issue, point them to that permission; there may be more work required by the Launchers, but that's for them to support. 

I have created a PR for the changes this app needs: #382. If anyone could test that branch out, I'd be most grateful.

**Comment by CDRussell** [comment]
@arunsathiya if you want to follow-up on your email to `Fastkey`, tell them they likely need to add this permission `com.android.launcher.action.INSTALL_SHORTCUT`. 

The permission is only used on newer OS versions (Oreo and newer, I think) so that's why `Fastkey` shortcuts work on older OS versions but not on newer ones.

**Comment by CDRussell** [comment]
Fixed by #382 

Thanks again all for your help in raising, diagnosing and solving the problem! 🎉

**Comment by arunsathiya** [comment]
@CDRussell I shall do that, thanks for getting to the bottom of this and fixing it! 🏆
