### ISSUE TITLE
Screenshot (Mar 24, 2024 1:07:44 AM) marquesawaresr@gmail.com

### ISSUE THREAD

**Issue by Mobility-Inc-Marq** [duckduckgo/Android#4353]
![Screenshot_20240324-010744.png](https://github.com/duckduckgo/Android/assets/151239242/479d86c0-be77-4276-bb8d-9191c578d878)

**Comment by karlenDimla** [comment]
Hello! This bug report is not actionable due to lack of any background or information. Please use the [Bug report template](https://github.com/duckduckgo/Android/blob/develop/.github/ISSUE_TEMPLATE/bug_report.yaml) when filing an issue (should be automatic when you choose New Issue > Bug Report) and provide the needed information for us to triage this bug accordingly. 

Closing this for now and feel free to reopen once more information is available.
