### ISSUE TITLE
Screenshot (Mar 25, 2024 10:29:47 PM)

### ISSUE THREAD

**Issue by Mobility-Inc-Marq** [duckduckgo/Android#4355]
![Screenshot_20240325-222947.png](https://github.com/duckduckgo/Android/assets/151239242/298bf841-2447-4e84-971e-55c9c1273eec)

Not Allowing to merge successfully with VPN for authentication.

**Comment by karlenDimla** [comment]
Hello! This bug report is not actionable due to lack of any background or information. Please use the [Bug report template](https://github.com/duckduckgo/Android/blob/develop/.github/ISSUE_TEMPLATE/bug_report.yaml) when filing an issue (should be automatic when you choose New Issue > Bug Report) and provide the needed information for us to triage this bug accordingly. 

Closing this for now and feel free to reopen once more information is available.
