### ISSUE TITLE
[Bug] It's possible to hide address bar on empty browser screen without possibility to undo it

### ISSUE THREAD

**Issue by pwittchen** [duckduckgo/Android#439]
**Steps to reproduce the issue**:

1. Open browser
2. Hide keyboard with back button
3. Slightly swipe up the address bar
4. Address bar is gone
5. There's no possibility to show it back again without closing and re-opening a browser

See gif below for details.

![duck-duck-go-bug](https://user-images.githubusercontent.com/695319/52698866-b91e6700-2f74-11e9-91b5-c1152d3072c9.gif)

**Comment by CDRussell** [comment]
This should be fixed in the latest release `5.18.0`. It is rolling out in the Play Store this very second, and should be widely available within the next 2 hours.

It is also available from the GitHub release page https://github.com/duckduckgo/Android/releases/tag/5.18.0

I will close this issue for now assuming the latest release solves this issue. But comment if it doesn't and i'll re-open.

Thanks for reporting it!
