### ISSUE TITLE
Improved "add to home"

### ISSUE THREAD

**Issue by chaptergy** [duckduckgo/Android#529]
Hey,

Currently, when you add something to the homescreen, it uses the URL as the icon name and sometimes has issues fetching the favicon. It would be better if it used the page title, or even better, let me define the name manually before adding it to the homescreen. Maybe even let me edit the url, in case they automatically append data to the url, which I don't want. And it would be great, if they'd use the touchicon first, before it uses the favicon or even no icon at all (just the duckduckgo icon)

Thanks a lot

**Comment by cmonfortep** [comment]
We have improved our favicon handling, hope that part of your issue is gone. 

However, for the other part of adding extra support to "add to home" we don't have short-term plans to do so. Currently we are using the native webview component for that and we would need to build our own dialogs. In any case, I will share it with the team in case we revisit that part. Thanks.
