### ISSUE TITLE
[Bug] search suggestions ignore -removals

### ISSUE THREAD

**Issue by Noitarud** [duckduckgo/Android#5387]
### Describe the bug

Ditto

### How to Reproduce

Enter Phone light -selfie

### Expected behavior

not get suggestions with selfie

### Environment

```markdown
- DDG App Version:5.216.2
- Device:all
- OS:android
```

**Comment by anikiki** [comment]
@Noitarud We closed the issue as there is no further action from us.

I see the expectation was for the search suggestions to filter out the word "selfie" when searching for "phone light -selfies". This is a fair feedback, thank you!

Advanced search options provided by search engines like DuckDuckGo support such filters, but it's not commonly integrated into browser suggestion functionalities.

**Comment by Noitarud** [comment]
@anikiki are you trying to dodge the request by rephrasing what I said? it is more honest to close it as "won't fix"

**Comment by anikiki** [comment]
@Noitarud It was not my intention to dismiss your request.

The issue was closed with a summary of the request and a short explanation on the current design and implementation scope of our suggestions functionality.

I added the "Won't fix" label. This has been acknowledged and will not be pursued further.
