### ISSUE TITLE
Unable to Install a downloaded APK from DuckDuckGo browser

### ISSUE THREAD

**Issue by FlorianSb** [duckduckgo/Android#580]
It is not Possible to install an APK after download with DuckDuckBrowser. I use build 5.32.1.53201 on linage OS 16. I have downloaded from F-Droid

**Comment by subsymbolic** [comment]
Hi @FlorianSb, I'm excited to hear that you're using linage OS. Unfortunately we don't yet support it, but hopefully will in the future.

**Comment by FlorianSb** [comment]
Thanks for your reply. But unfortunately same Issue on Stock Android.

**Comment by CDRussell** [comment]
@florianSb, do you mean you can install our app fine, but when you download an APK using it, you can't install it? Is that right?

If so, it's likely because of the app installation permission added in Oreo or Pie. There's an additional permission we need to add so that we can do what you're asking IIRC. We can look into it and see if it's something we want to add.

Or, if that's not what you're describing, please give more details.

Thanks
