### ISSUE TITLE
widget: transparent background

### ISSUE THREAD

**Issue by francescosoave** [duckduckgo/Android#662]
Hello, I'd like to suggest a feature to allow useras to have a transparent widget. As you can see the screenshot below, to have the grey part fully transparent with only the icons showing.

![Screenshot_20191226-140113_1](https://user-images.githubusercontent.com/26126452/71483726-79b5dd80-2809-11ea-84ba-7606b3294846.jpg)

**Comment by mnp** [comment]
I like this design, because while we're talking about the widget I have two points.

1. Why is it a long widget styled to look like a text entry field? I would really like to click directly into it as a search bar, have the keyboard pop up right on the home screen, and slam a query in there, flipping to the app for results. Instead, it's just a long button that takes you to the app where the query entry happens. So you're mentally in "type query" mode on the home page, then you're thinking "oh wait, we're going to the app", wait for that to load, then you're back in "type query" mode. I like OP's widget because it's obviously a button and not a fake search box.
2. I also like OP's widget because it's ~2x1 instead 5x1, less real estate for an actual button.

**Comment by cmonfortep** [comment]
We have a project in our backlog (internal task https://app.asana.com/0/715106103902962/1200110974677898/f).

That project will introduce many improvements I don't want to spoil. But one of them it's to be able to resize the widget and something related to colors. 

Closing this issue as it's already in our backlog. :)
