### ISSUE TITLE
Play video in landscape when the video is shape is landscape.

### ISSUE THREAD

**Issue by stevenleeS0ht** [duckduckgo/Android#676]
Currently, when disable auto-rotate option in Android system.  duckduckgo-android will play all video in portrait in fullscreen mode. 

However, this is not good for video watching.

I would like to recommend that at the moment of touching fullscreen button in the web page. When the device is placed in landscape, Then if the video's shape is landscape, then it will be played in landscape. Otherwise it will be played in portrait.

I am not sure if I described it correctly. 

But currently, Chrome and Firefox Preview have this feature.

Please have a try for reference.

**Comment by stevenleeS0ht** [comment]
@CDRussell , @subsymbolic , What is your opinion?

**Comment by cmonfortep** [comment]
Thanks for submitting this @stevenleeS0ht. I'm going to mark this issue as `enhancement`.

Friendly reminder, in case anyone is willing to help here submitting a PR, according to our [contributing](CONTRIBUTING.md) guidelines, please mention your intention first. If it fits with our product direction and is a good candidate for community development we will happily accept the contribution.

**Comment by Poopooracoocoo** [comment]
IIRC DDG Browser for Android is based on Chromium.

I have a link to the appropriate Chromium issue on their Gerrit in one of my issues. Could someone please link that issue? It's the one related to JW Player.

I had no idea Firefox Fenix finally added that! It's a shame that Focus is being neglected by Mozilla and has critical bugs. In fact, that's why I'm here! DDG Browser is like a better version of FF Focus that keeps my tabs but it still needs to improve.

Just a question: you're referring to the native player, right? Do videos on the YouTube mobile site rotate? That uses a custom player so we have to make sure.

**Comment by cmonfortep** [comment]
Hello there. We have received similar feedback and we are collecting everything related to videos internally. 

Everyone can continue sending feedback via our embedded form within the app (inside settings) or just using the web form.  We process that feedback internally and scope projects when we see enough activity. 

Closing this issue as it's already tracked internally. Thanks.

Check "share feedback" guidelines here (https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md#share-feedback).
