### ISSUE TITLE
Tap and hold back button to view tab history 

### ISSUE THREAD

**Issue by Poopooracoocoo** [duckduckgo/Android#682]
Bonus: tap and hold back and forward buttons in menu to see history

**Comment by AndrewR8** [comment]
I would like to work on this issue.

**Comment by Poopooracoocoo** [comment]
@AndrewR8 there's a similar Firefox (Fenix) issue. 

In a nutshell, it's a good idea to show back and forward history in one menu when a user taps and holds on the forward button. The back button can keep the back stack but that might be too much to implement. The problem is Android 10's gestures. I'd love to know what you want.

**Comment by cmonfortep** [comment]
@AndrewR8 thanks for volunteering to tackle this enhancement, but I think this is one of those projects we should implement internally due to the amount of needed collaboration with product and design team.

I keep this issue open here till we discard or accept the idea and to communicate any future updates to users that may be interested.
