### ISSUE TITLE
duckduckgo android not opening properly after changing icon 

### ISSUE THREAD

**Issue by ghost** [duckduckgo/Android#774]
hi when I change the icon on the duckduckgo android app it won't open properly
 
steps to reproduce:
1)open duckduckgo

2) open the settings option

3) change the icon 

4) restart the app by reopening and closing the app 

5) duckduckgo no longer opens
<img width="908" alt="duckduckgo github issue bug" src="https://user-images.githubusercontent.com/41688975/78999949-afad7200-7b19-11ea-9387-bb1204ead8a3.PNG">

PLATFORM/DEVICE: blue stacks android emulator on windows 10

**Comment by epicodertime** [comment]
the emulator runs a version of Android 7.1.2

**Comment by epicodertime** [comment]
workout to bypass the broken duckduckgo: go to google play and click open and then it works but if we open it using the home screen it doesn't work

**Comment by cmonfortep** [comment]
We haven't received any similar feedback coming from users using an android device (we tested that Android version too), so the issue may be related to something internal with`BlueStacks` emulator. We will try to take a look, but I can't promise you a quick response here 🙏.

Thanks for reporting the issue in any case.

**Comment by bruhmoment-web** [comment]
hey @cmonfortep I found a vulnerability on the duckduckgo Andriod app I reported it via HackerOne, however, the HackerOne staff member doesn't think its a security flaw but can you check to see if its a valid vulnerability my ticket number is #856791 


impact
The issue is that the auth popup belongs to the attacker's tab, but it is being shown in the context of the current tab (google.com). The risk is that a user thinks that google.com is asking for credentials and enters their google password in the attacker-controlled popup.

2 attachments:
![Inkedbruh duckdudckgo s_LI](https://user-images.githubusercontent.com/63518091/80262669-3145e980-865c-11ea-9994-17948452f5f3.jpg)

**Comment by cmonfortep** [comment]
@bruhmoment-web I will follow up and triage if there's any vulnerability in HackerOne. It's the place to report any vulnerability according to our guidelines, and the place where we will able to ask you more about the issue (app version, steps to reproduce, etc.) if we consider it's necessary.

I will remove the previous comment from this issue as it's in the wrong place. I will also remove my comment at some point. I will keep it for a prudential time just to be sure you are able to read it. Thanks.
