### ISSUE TITLE
Please add web page dark mode

### ISSUE THREAD

**Issue by rogerxed** [duckduckgo/Android#840]
Please add web page dark mode like opera browser, dark mode will reduce eye stress.

![Screenshot_20200525-212242](https://user-images.githubusercontent.com/65120278/82828237-39e54600-9ece-11ea-86cc-fdf91cf97b84.png)

**Comment by KelvnPere** [comment]
Hi @cmonfortep I would love to work on this enhancement request.

**Comment by cmonfortep** [comment]
Hi @KelvnPere, thanks for offering yourself to work on this. First, let me ask our product team about introducing this enhancement, and if they agree is something we can introduce I will ping you here.

@rogerxed just to clarify, are we talking about forcing the website to use dark mode when dark mode is enabled in our app, right?

**Comment by KelvnPere** [comment]
That would be great @cmonfortep. Are they some minor fixes that help is needed. If any kindly drop a link. Thanks

**Comment by rogerxed** [comment]
> That would be great @cmonfortep. Are they some minor fixes that help is needed. If any kindly drop a link. Thanks

Yes, Of course.

**Comment by rogerxed** [comment]
> Hi @KelvnPere, thanks for offering yourself to work on this. First, let me ask our product team about introducing this enhancement, and if they agree is something we can introduce I will ping you here.
> 
> @rogerxed just to clarify, we are talking about forcing the website to use dark mode when dark mode is enabled in our app, right?

Yes, Of course.

**Comment by cmonfortep** [comment]
Hi there @KelvnPere and others. I've been sharing this proposal with other members of the team and we need to explore this a bit more.

Basically, there are some sites where users could choose their own theme from the website settings, and we don't want to override those settings forcing the webview to use dark theme in some scenarios. A real example is DDG, users that visit our website, they can configure their them from https://duckduckgo.com/settings#theme 

We are open for suggestions about how to solve that usecase, I haven't had time to explore if there's any way to avoid webview overriding website settings.

**Comment by sanogueralorenzo** [comment]
😱 Completely missed this issue before trying something out I opened a PR with a GIF showcasing it in case anyone wants to play around https://github.com/duckduckgo/Android/pull/848

Regarding your comment @cmonfortep it is a good point (although I haven't' personally faced it due to not using Themes on my end). When I had some issues with DarkMode on Kiwi Browser I just tend to remove it for that page the same way I would remove an Adblocker or use the whitelist feature from duckduckgo.

Instead of just being a switch in settings it could be a separate page to include exceptions and also extend from On/Off to also include Automatic so it changes at night (same with the light/dark theme).

![DuckDuckGo-DarkMode-GitHub-PR](https://user-images.githubusercontent.com/5630683/83954062-a62f4600-a7fa-11ea-9211-56b2104bd279.gif)

**Comment by cmonfortep** [comment]
Hey @sanogueralorenzo, I've just tried kiwi browser on Android: I can change the theme but webview is not changing for me, am I missing something? Neither I see any allow/deny list to introduce any rules on where to apply themes per site.

Related to your PR I will comment directly there with more details, but our priority is to keep any preference set by the user on any websites. In any case, I may use your PR to try it and see if there's any workaround to keep the folowwing priority: first website theme, second browser theme.

**Comment by sanogueralorenzo** [comment]
@cmonfortep in Kiwi it is in the top-level menu as "Turn on  Night mode"

![image](https://user-images.githubusercontent.com/5630683/84056266-d564c500-a96a-11ea-9e3e-f2f402e96fc0.png)

Regarding the website theme I'm not sure how that is possible. When I mentioned the Allow/Deny list it is something I haven't seen implemented for Dark Mode (since you can just turn it off if something doesn't look right).

I was comparing it to the Allow/Deny list you have for Tracking for example. It would be a matter of extracting the domain of the URL to invert the theme if dark theme is enabled.

Not sure how many people would use that though, does the retain themes in darkmode have more weight than enabling the option (opt-in through settings) of dark mode?

**Comment by cmonfortep** [comment]
Thanks for clarifying how to enable that option in kiwi browser. I played with it and I didn't like how some websites are rendered when forcing them to use dark theme. That means we can't automatically force the webview to be dark based on the app theme.

Most probably we will need to let the user decide in the same way as kiwi does it, with an option in the overflow menu, or like your proposed (inside settings), or any other way. That increases our initial scope, and it will involve product decisions and reviews. I will try to follow up this with them, to see if I can get some opinions around what's the preferred way to present this to users.

In any case, worth saying that we already have a project scoped to improve Dark theme experience in our backlog, but it's not on our top priorities right now. That could change if we see many users requesting this feature.

**Comment by ejortegau** [comment]
https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh is IMHO the best implementation of darkening of web content. It has multiple modes that can be set per site, and also allows for skipping darkening altogether for some sites. I'd advise considering this as a main source of inspiration as opposed to the opera or kiwi alternatives.

**Comment by cmonfortep** [comment]
Sadly, I've been reviewing what's the current status of WebView to support Dark mode, and testing it within our app, and WebView does not correctly supports dark mode according to our requirements. They do for Chromium.
Currently, WebView let you force dark theme on websites but in a way that doesn't respect the site's branding colors or selected theme.

I was going to open them an issue but found a few ones related:
https://bugs.chromium.org/p/chromium/issues/detail?id=1061152
https://bugs.chromium.org/p/chromium/issues/detail?id=964594

We have documented this WebView limitation to review it in the future. For now, I will close this issue until Webview provides us a way for changing to dark mode honoring website's dark theme.

**Comment by oldphones68** [comment]
Is there any update from WebView side? @cmonfortep

**Comment by pc00per** [comment]
I don't think DDG well ever get dark mode, because of the bugs you're referring to. As for the dark mode itself, if you chose to atleast force render CSS, you could've make it work despite of the site specific colors not being respected. That's how the dark mode should be. Why would it respect site's background color, when user explicitly defines it to be dark?

**Comment by vishaluchil** [comment]
@cmonfortep Any update on this? 2022 is coming to an end, and I feel this a feature that should take priority. Love using DDG but this a feature I have been hoping to have since a really long time

**Comment by howardcochran** [comment]
I am sad to see this closed. I think the option needs to be present, even if there are some bugs.  I was excited to discover DDG, but must switch back to Chrome, because Dark view of web pages is an absolute requirement for me, and Chrome has been doing it for years now.
