### ISSUE TITLE
Use External Download Managers

### ISSUE THREAD

**Issue by jawadalkassim** [duckduckgo/Android#865]
Use ADM or IDM as an external download manager. So we download a file from the browser should have an option to choose which program i will download with (DDG or Any other external download manager)
This feature is available at Firefox Android

**Comment by cmonfortep** [comment]
Hi @jawadalkassim, we don't have plans for giving support to other download managers.
Since I'm not familiar with other download managers, do you mind sharing with us some clear benefits? For example: benefits related with privacy or other browser-specific use cases that our users could benefit from, etc.

We have a big backlog of new features and it's important for us to understand the impact a feature request can have in order to discard or to prioritize it. I don't think this is likely to happen since we already cover downloading files with ADM, but happy to know more about it.

**Comment by jawadalkassim** [comment]
Hi @cmonfortep, Sorry for Responding late, actually the main advantage of this, downloading large files with slow internet can be a little messy with android or any browser download manager. So forwarding this download to ADM is more helpful.

**Comment by cmonfortep** [comment]
We created an internal task to move away from the Download manager as it will help us solve other issues. 

Internal task: https://app.asana.com/0/414730916066338/1199350832762474/f

**Comment by cmonfortep** [comment]
Internal task: https://app.asana.com/0/0/1199514257586722/f

**Comment by vickyoo7** [comment]
> Hi @jawadalkassim, we don't have plans for giving support to other download managers.
> Since I'm not familiar with other download managers, do you mind sharing with us some clear benefits? For example: benefits related with privacy or other browser-specific use cases that our users could benefit from, etc.
> 
> We have a big backlog of new features and it's important for us to understand the impact a feature request can have in order to discard or to prioritize it. I don't think this is likely to happen since we already cover downloading files with ADM, but happy to know more about it.

Hi @cmonfortep, I'm the developer of 1DM (formerly IDM) with more than 15 million users. Many of my users have requested me to add support for DDG browser. If you're still interested in adding support for external downloaders (1DM) please let me know i can provide you the intent details. Thanks
