### ISSUE TITLE
Website title / description ommited when using "Share" function

### ISSUE THREAD

**Issue by ecklebrug** [duckduckgo/Android#870]
1. What I do:
Share a certain URL, a news article for example - "Charlie Chaplin first man on the moon!" (news.kom/chaplinmoon.html) - with any messenger or Nextcloud Bookmarks.

2. What happens:
Only the URL is passed along: news.kom/chaplinmoon.html

3. What should happen:
Title / Description and URL show up in messenger or bookmarks app:
"Charlie Chaplin first man on the moon!" -news.kom/chaplinmoon.html

(Sorry, if this is the wrong label. Not sure, if bug or missing feature.)

**Comment by donfuxx** [comment]
It seems like the behaviour of ddg is consistent with Google Chrome though, which would only share the url as well.

**Comment by ecklebrug** [comment]
When sharing via Google Chrome, the description is visible:

"Why restaurant menus are getting shorter - CNN - https://www.cnn.com/2020/06/23/business/restaurant-menus-shrinking/index.html"

**Comment by cmonfortep** [comment]
Hi @ecklebrug, I guess the expected behavior can be different for each user.

In my case, I like that we only share the URL when sharing a link via any messenger app (sometimes that messenger app will show a preview of the link). For a few other cases like you described, it could be helpful to share that extra info, for example sharing a link via email (adding that title/description to the subject).

Since sharing is already covered but not as some users may expect, I'm going to label this issue as "Feedback" in case we can revisit our sharing functionality.

Thanks for reporting it.
