### ISSUE TITLE
Reporting privacy concern

### ISSUE THREAD

**Issue by gowthamgts** [duckduckgo/Android#876]
This is related to #527.

Users like me don't care much about favicons and we're using your browser only for privacy reasons. As a browser advertising that you respect user's privacy, please don't do things like this:

https://github.com/duckduckgo/Android/blob/ed91c9e551d2a9e1559199f110bd94c076784c71/app/src/main/java/com/duckduckgo/app/global/UriExtension.kt#L60

Either move this favicon logic to here (guessing that won't be hard?) or as others mentioned:

```
Take the code from Firefox iOS or Android-components. We spent a lot of time on these and it is all on device.

https://github.com/mozilla-mobile/android-components

https://github.com/mozilla-mobile/Firefox-iOS 
```

**Comment by gowthamgts** [comment]
Also, I do not understand how this is relevant now. All these URLs return the same image:

1. https://icons.duckduckgo.com/ip3/google.ico
2. https://icons.duckduckgo.com/ip3/facebook.ico
3. https://icons.duckduckgo.com/ip3/asdasdasdasdasdsad.ico

**Comment by cmonfortep** [comment]
Thanks @gowthamgts for opening this issue and also sharing the Mozilla reference with us. 

I'm happy to say that we have re-opened the previous issue. In order to avoid duplicated comments, and to have all user's comments in one single place, I will be closing this one as duplicate.

Please refer to this issue for future updates and feel free to comment in there -> https://github.com/duckduckgo/Android/issues/527
