### ISSUE TITLE
"Add to Whitelist" in Menu Not Clearly Worded - "Privacy Protection" is Unclear

### ISSUE THREAD

**Issue by landry314** [duckduckgo/Android#880]
In the menu the option "Add to Whitelist" was not clear to me at first because in Settings it is called "Privacy Protection Whitelist". I think these should be renamed to be more similar. "Privacy Whitelist" in the menu is more clear.

I am not even sure what this is. Are the blocked trackers related to this or is it totally separate? "upgraded by Privacy Protection" is not a clear way to describe this. Upgraded? I feel like the words used for this feature should be rethought.

"Fireproof Websites" protects cookies. That is cute and clear... maybe there is a way to describe this similarly. "Privacy Protector Disabled" or "Unprotected Websites" or something like this...

I am not sure if trackers are involved in this so... I can't come up with the best way to describe it. Let's discuss.

**Comment by cmonfortep** [comment]
Hi @landry314, thanks for sharing this feedback with us. Also for the Fireproof websites reference as "cute and clear", which makes me happy as I've been involved on the project :D

That being said, I'm happy to share with you that we already merged a change to improve what you described (https://github.com/duckduckgo/Android/pull/867 -> it will be out in our next release). We will be using something more clear like "unprotected websites" and "enable privacy protection". Hope the feature will be more clear with that change. It seems that we are on the right path as you suggested a similar concept to be used 🚀 

Thanks!

**Comment by landry314** [comment]
That's good to hear!

Does "Site Privacy Protection" on the Privacy Dashboard have anything to do with the trackers blocked on that same page? There is switch on the page to turn Privacy Protection on and off but it is not clear if that is related to the trackers or not. This could be clearer too. Maybe the place it says the numbers of trackers blocked will change in a different way as you hit the switch instead of just turning gray. Like saying "Tracker Blocking Disabled". Again, I am not sure what is even happening... that is why I opened this issue!

**Comment by cmonfortep** [comment]
> Does "Site Privacy Protection" on the Privacy Dashboard have anything to do with the trackers blocked on that same page?

Yes, that switch enables or disables our privacy protection in the site you are visiting, and that includes our tracker blocking.

You are right, we could update somehow the UI to make more clear what's happening. Currently, we only change icon background color (the above "Enhanced from X to Y") from green to grey, but I can see why that's not clear enough. About changing the number of trackers blocked when you change the switch, we need to reload the site to know that number, that's why you could see the real number if you go back to the browser and check the privacy dashboard again. But good call.

I'm going to take your feedback and share it internally. Yet, I'm not sure if we will apply changes to current screen in the short term. The reason is that we know that it needs to be improved and there are some proposals to change it from scratch and build a new one. But who knows! maybe we end up finding some time to introduce some quick changes to the current screen.

Thanks for sharing not only those ideas but also the things that you would expect to see in there.

**Comment by cmonfortep** [comment]
I think we can close this issue. As I commented, we updated the copies we used around our privacy protection.

Here's some screenshot from the overflow menu:
<img src="https://user-images.githubusercontent.com/4747865/96236916-ef5b8780-0f9c-11eb-8391-f64f29a54227.png" width="200px"/>
and
<img src="https://user-images.githubusercontent.com/4747865/96236939-f71b2c00-0f9c-11eb-8ed0-b467cfdb3090.png" width="200px"/>

And related to the feedback received around the privacy dashboard screen, we are currently resisting that screen under another project: https://app.asana.com/0/72649045549333/1178508602409417/f

Thanks.
