### ISSUE TITLE
DDG 5.59.0 crash report error on Samsung device health service

### ISSUE THREAD

**Issue by runboy93** [duckduckgo/Android#884]
Samsung device health service show DDG 5.59.0 version causes crashes (doesn't show in use anyway, only when see error history on Samsung device health service)

Open DDG 5.59.0, fire information and close app.

Samsung device health service > 3 dots > apps error reports history

With DDG version 5.59.0, each time you start / stop app, it does show error report (only time when it happens, and that app has crashed, no logs)

When using earlier version, such as 5.58.1 or 5.58.0, such error crash report doesn't happen, so something is wrong with exactly DDG version 5.59.0.

 - DDG App Version: 5.59.0
 - Device: Samsung Galaxy A71
 - OS: Android 10

**Comment by cmonfortep** [comment]
Thanks for reporting this. We got some crash reports after publishing 5.59.0 and merged a PR fixing the problem: https://github.com/duckduckgo/Android/pull/881

It was not clear to us how to reproduce that crash, but the information you provided has been really helpful to understand better the problem.

The fix is available in 5.59.1 release.

Closing the issue.
