### ISSUE TITLE
Support Web Bluetooth API

### ISSUE THREAD

**Issue by Phoenix616** [duckduckgo/Android#894]
**Is your feature request related to a problem? Please describe.**
Websites which use the [Web Bluetooth API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API) do not work due to that API not being provided.

**Describe the solution or the user experience you'd like**
For websites using that API to work.

**Additional context**
Web Bluetooth API spec: https://webbluetoothcg.github.io/web-bluetooth/

**Comment by cmonfortep** [comment]
Thanks, I see that is not supported by Android Webview according to the [Docs](https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API#Browser_compatibility).

Our browser is based on the Android Webview, so I'm not sure we can support it by ourselves. I still need to explore more on this (I've created an task in our backlog https://app.asana.com/0/0/1188018485640065/f ).

If anyone has more info about this, feel free to share it here. Thanks!

**Comment by cmonfortep** [comment]
Closing this as WebView does not support according to Docs and I haven't found a way to support this in our browser.

**Comment by Phoenix616** [comment]
Don't get why this should be closed then if it isn't fixed? Doesn't this just hide the issues from others that are willing to look into it and are maybe able to find a solution?

**Comment by cmonfortep** [comment]
I've currently reviewing the status of our open issues. For this concrete one, I tried to find a solution without any luck.

Our browser is based on WebView, and if WebView does no support that bluetooth API, I'm pretty confident there's nothing else we can do here. I also noticed that the API is experimental, something that will add complexity to this task (validating that is safe and no security issues are introduced).

Without a valid approach, we can't triage or prioritize this request, and since I haven't seen any further activity here, I think is ok to close it for now.

**Comment by Phoenix616** [comment]
I just don't understand why issues that aren't resolved or otherwise invalid should be closed.

Other people might run into this API missing as well, not see an open one and just open a new one about the same issue instead of simply commenting on/subscribing to this one.

Also I think if this stays open it can be used to point the developers of WebView to it and to close once WebView implemented it (or someone found a workaround) and with that notify anyone who is interested in this same issue.
