### ISSUE TITLE
Design And Features

### ISSUE THREAD

**Issue by WillHick** [duckduckgo/Android#915]
A Few Possible Ideas

Design:
• On Larger Devices (Tablets), The Search Box is Not Rounded As Much As Mobile And Goes More Towards A Rectangle
• Darken The Privacy Dashboard And In App Popup Dialogs And Menus (Clear Data Menu, Clear On Dialog, Automatically Clear Dialog And The Tab Menu)

Update:
• Have An Option To Move The Toolbar To The Bottom For Larger Displays

Features For Security And Personalization:
• More Site Information In Privacy Dashboard (E.g. If You Press On Site Connection You Can Access More Site Info)
• Web Settings (Enable/Disable Javascript, Cookie Types, Form Data Etc)
• Improve Ad/Tracker Blocking
• Some Sort Of Download Protection (Block Automatic Downloads Or Allow Them Through Settings)

Possible:
• Move DDG To GeckoView

Thanks

**Comment by cmonfortep** [comment]
Thanks for sharing all those ideas.

Design:
- Search Box: will check with designers if that's intended or something to fix.
- Dark theme improvements: duplicated from https://github.com/duckduckgo/Android/issues/660 FYI: It's in our backlog to improve dark theme support, however difficult to prioritize for a small team (included designers). Privacy dashboard may be 100% redesigned, so we are putting on hold new changes there.

Update:
- We tested that and it didn't have enough impact on our users. We know some of you folks like it, but since it didn't have as impact as we expected, we prefer to maintain (code-wise) one single UI distribution than multiple ones.

Security and personalization:
- Could you file a new issue for that enhancement? I would like more about it and what would you like to have as a user. Thanks!
- Could you file a new issue for this web settings? and explain further each of them? Thanks!
- We focus on blocking ads that track users, not all the ads that may appear on a website.
- Block Automatic Downloads: this should be the case. If you click on a link, we will request permissions or show a dialog, is it not the case for you?

- GeckoView: we have considered that many times, but for now we don't have plans to move into GeckoView.  

I will close this issue as we prefer to have one issue per topic. Hope that's ok!
