### ISSUE TITLE
New Tab Page

### ISSUE THREAD

**Issue by WillHick** [duckduckgo/Android#987]
Could this make a potential come back as a New Tab Page Design?

![IMG_20201101_204700](https://user-images.githubusercontent.com/48844761/97797633-6b371e80-1c83-11eb-9176-e7bf7e1a03dc.jpg)

**Comment by cmonfortep** [comment]
Hi @WillHick, I don't think so 😅
 
We removed that search bar a long time ago, and we are also thinking about redesigning our new page tab. Also, IIRC iOS also removed that bar from their new page tab because our URL bar does the same.

In any case, could you share with us why you prefer that new page screen instead of the current one? is there any usecase we are not covering for you? Thanks!

**Comment by WillHick** [comment]
@cmonfortep Im aware this is an older design 😂

It looks like it would fit well for a New Tab Page if it was designed to fit well with current versions, instead of using the search bar on a New Tab.

**Comment by cmonfortep** [comment]
Thanks. As I said we will work on a new design for that new tab screen, so expect some new exciting changes on that screen at some point 👍
